global using Big2.Domain.Enums;
global using Big2.Domain.Exceptions;
global using Big2.Domain.Mementos;
global using Big2.Domain.ValueObjects;
global using Big2.Domain.Service.Rules;
global using Big2.Domain.Service.Scoring;
global using Big2.Domain.SeedWorks;
global using Big2.Domain.Extension;
global using System.Linq;